#!/usr/bin/env ansible-playbook
#
# test playbook
#
---
- import_playbook: ../ssh-key-mgmt.yml

- name: Create temp directories
  hosts: localhost
  connection: local
  tasks:
  - name: delete temp directory structure if present
    file:
      path: /tmp/reportdata/
      state: absent
  - name: create data directory
    file:
      path: /tmp/reportdata/data
      state: directory

- name: Capture datetimestamp
  hosts: localhost
  tasks:
  - set_fact: datetimestamp="{{ lookup('pipe', 'date +%Y-%m-%d-%H%M%S') }}"

- name: Prepare JSON report header and footer files
  hosts: localhost
  connection: local
  tasks:
  - name: create header file
    file:
      path: "/tmp/reportdata/00-iosfacts.{{ datetimestamp }}.header.json"
      state: touch
  - lineinfile:
      dest: "/tmp/reportdata/00-iosfacts.{{ datetimestamp }}.header.json"
      line: '{"ipv4addrs": {'
  - name: create footer file
    file:
      path: "/tmp/reportdata/zz-iosfacts.{{ datetimestamp }}.footer.json"
      state: touch
  - lineinfile:
      dest: "/tmp/reportdata/zz-iosfacts.{{ datetimestamp }}.footer.json"
      line: "}}"

- name: get facts from ios-xe
  hosts: pe
  vars_files:
   - "/etc/ansible/custom_vars/info.yml"
  tasks:
  - ios_facts: 
      provider: "{{ prodcli }}"
  - debug: var=ansible_net_all_ipv4_addresses
  - copy:
      content: '"{{ inventory_hostname }}": {{ ansible_net_all_ipv4_addresses | to_json }}'
      dest: "/tmp/reportdata/data/{{ inventory_hostname }}.txt"

- name: assemble data output files into a single intermediate file
  hosts: localhost
  connection: local
  tasks:
  - assemble:
      src: /tmp/reportdata/data
      dest: /tmp/reportdata/iosfacts_report.json
      delimiter: ","

- name: assemble data and header files into the json-formatted report
  hosts: localhost
  connection: local
  tasks:
  - assemble:
      src: /tmp/reportdata/
      dest: "~/iosfacts.{{ datetimestamp }}.json"
