#!/usr/bin/env ansible-playbook
#
# Example of a password change playbook that uses ansible-vault to protect
# current and new credentials
#
# file: /etc/ansible/group_vars/l1-ios.yml (one file in group_vars for each group)
#---
## secrets for ios-xe devices
#secretxecli:
#  username: labadmin
#  password: currentpassword
#  auth_pass: current_enablepassword
#newpass: new_password
#
#
# to edit a file that has been encrypted with ansible-vault:
# ansible-vault edit l1-ios.yml
#
# to encrypt a file that already exists:
# ansible-vault encrypt l1-ios.yml
#
# to run a playbook that has ansible-vault-encrypted vars:
# ansible-playbook changepass.yml --ask-vault-pass
#
---
- import_playbook: ssh-key-mgmt.yml

- name: Change local admin password on IOS-XE devices
  hosts: l1-ios
  tags: xe
  tasks:
  - name: change password on IOS-XE boxes
    ios_config:
      authorize: yes
      provider: "{{ secretxecli }}"
      lines:
        - "username labadmin privilege 15 secret {{ newpass }}"
      save_when: always

- name: Change local admin password on IOS-XR devices
  hosts: l1-xr
  tags: xr
  tasks:
  - name: change password on IOS-XR boxes
    iosxr_config:
      provider: "{{ secretxrcli }}"
      admin: yes
      parents: username labadmin
      lines:
        - "secret {{ newpass }}"
